#+TITLE: Physics and Computation
#+AUTHOR: Yusheng Zhao
#+OPTIONS: toc:nil

* Disclaimer
Yes, chatgpt is good at spitting out nonsense. But I used it to proof-read and
polish my essay.

* Quantum Computation: A plagued technology
Quantum computers possess the capability to solve certain problems with greater
efficiency than classical computers. Shor's algorithm, for instance, can factor
large integers $N$ in $\mathcal{O}(log(N)^2 loglog(N))$ time, whereas the most
efficient classical algorithm is $\mathcal{O}(e^(1.9 log(N)^(1/3)
loglog(N)^(2/3)))$ [[cite:&ShorAlgorithm2023]]. Consequently, quantum computers have
the potential to provide exponential speedup for factoring large integers.
However, modern encryption techniques that rely on the difficulty of factoring
integers are unlikely to be compromised anytime soon.

One of the most significant challenges in quantum computing is noise. In
essence, noise refers to a disruptive force that perturbs the qubits used for
computation. It is analogous to a mischievous imp that upsets the abacus one
uses for arithmetic operations. In other words, computation results from a noisy
quantum computer are no longer precise. These noises arise from unwanted
physical interactions between the qubits undergoing coherent evolution and their
environment or poorly calibrated operations used for computation.

Although techniques such as quantum error correction code can protect data in a
fault-tolerant quantum memory, they rely on relatively good physical operations
[[cite:&girvinIntroductionQuantumError2022]]. Presently, our technology is still
struggling to keep up [[cite:&kitaevUnpairedMajoranaFermions2001]]. Consequently,
there is a need to develop a naturally robust computing approach that is immune
to unwanted interactions causing noise.

* Topological Invariant: Physical Motivation
As Rolf Landauer said, "Information is Physical". When we do computation, we
first encode the information on physical systems and evolve those systems to
carry out computation. In our case, if we could find a physical system that is
inheriently immune to noise and encode information there, we would have a
naturally fault-tolerant quantum computer. At this stage, we realize that all
physical interactions we know are local. Meaning, an unwanted physical
interaction could only perturb physical entities that are close. If we could
find a way to encode a unit of information, quit, onto physically seperated
systems, such encoding will be tolerant to the kind of noise that roots from
unwanted local interactions.

Convinently, we know something that cannot be perturbed by local physical
interactions. Recall our definition of topological invariant in class. It's
defined as integral of over the entire surface. Hence, it's value is determined
by not only locally what's the curvature but also the curvature globally.

To be more concrete, say we put a two-dimensional system on a torus. The ground
state of that 2D system will be degenerate. Nevertheless, we could not
distinguish between the ground states by a local measurement due to the
existence of a topological phase which also indicates the non-existence of a
local order parameter. Hence, we could use these ground states as computational
basis of quantum computation. Any local measurement cannot distinguish between
the ground states. Therefore, they cannot decohere them. Making our information
topologically protected.

* Majorana Zero Mode: Physical Realization
As an example of a physical system protected by topological invariant, we
examine the toy model constructed by Alexi Kitaev in his seminal work. We notice
that two "half" fermion emerge on the boundary of the $1D$ chain. ... This is
exactly the topological

* Bibliography
** References
   :PROPERTIES:
   :beamer_opt: allowframebreaks
   :END:
   bibliographystyle:apalike
   [[bibliography:./finalp.bib][bibliography:./finalp.bib]]
